### ISSUE TITLE
2 auto clickers same hot key problem

### ISSUE THREAD

**Issue by MossaicTyler** [inket/Autoclick#14]
Hello @inket ,
So basically I downloaded 2 auto clickers for right and left click but realised the hotkeys were the same even if you changed them, is there a fix to this?
Kind regards,
Tyler

**Comment by MossaicTyler** [comment]
<img width="659" alt="Screenshot 2021-12-20 at 22 03 21" src="https://user-images.githubusercontent.com/96447195/146838596-93e8041b-2ccd-467a-ae3e-f07522071086.png">

**Comment by inket** [comment]
This is because they use the same storage for the settings. You can circumvent this:

1. Make a copy of Autoclick.app and name it Autoclick2.app
2. Change the bundle identifier of Autoclick2.app, should be inside the Info.plist file or use this command:
```
defaults write /Applications/Autoclick2.app/Contents/Info.plist CFBundleIdentifier jp.mahdi.Autoclick2
```
3. Remove the codesigning to be able to open the app:
```
codesign --remove-signature /Applications/Autoclick2.app
```
4. Open Autoclick2 by right-clicking then selecting "Open"
