### ISSUE TITLE
Autoclick 2 seems doesn't work on Catalina

### ISSUE THREAD

**Issue by nstylec** [inket/Autoclick#3]
macOS version : 10.15.7
The software version issued : 2.0.3
Issue describe :  the old version 1.0 actually works fine on Catalina with few sudden quit a week. But the version 2.0 and above doesn't work on it. Even I have already give accessibility permission to Autoclick, this version still ask me for setting adjustment.

**Comment by inket** [comment]
Can you remove all versions of Autoclick from your computer, then restart and install 2.0?
If it asks for the Accessibility permission after that, allow it then restart Autoclick and see if it works?
If all of that still doesn't work, I suggest you restart your computer again.

I believe macOS is confused about the permissions since I've had this issue during development too. After messing around with it for an hour a simple restart fixed it…

Please tell me if it's not fixed, I might add something to skip the setting adjustment. (but I still can't guarantee that it would work…)
